// Copyright Matthias Koch, Sebastian Karasek 2018.
// Distributed under the MIT License.
// https://github.com/nuke-build/kubernetes/blob/master/LICENSE

using System;
using System.Linq;
using FluentAssertions;
using Xunit;

namespace Nuke.Helm.Generator.Tests.Parsing
{
    public class DefinitionMarkdownParserTests
    {
        private readonly string[] _definitionLines =
        {
            "## helm lint",
            "",
            "examines a chart for possible issues",
            "",
            "### Synopsis",
            "This command takes a path to a chart and runs a series of tests to verify that",
            "the chart is well-formed.",
            "",
            "",
            "```",
            "helm lint [flags] PATH",
            "```",
            "### SEE ALSO",
            "* [helm](helm.md)	 - The Helm package manager for Kubernetes.",
            "###### Auto generated by spf13/cobra on 25-Jul-2018"
        };

        [Fact]
        public void Should_ParseDescription()
        {
            var definition = DefinitionMarkdownParser.Parse(_definitionLines);
            definition.Description.Should()
                .Be("This command takes a path to a chart and runs a series of tests to verify that\nthe chart is well-formed.");
        }

        [Fact]
        public void Should_ParseSynopsis()
        {
            var definition = DefinitionMarkdownParser.Parse(_definitionLines);
            definition.Synopsis.Should().Be("helm lint [flags] PATH");
        }

        [Fact]
        public void Should_ParseSeeAlso()
        {
            var definition = DefinitionMarkdownParser.Parse(_definitionLines);
            definition.SeeAlso.Should().Equal("* [helm](helm.md)	 - The Helm package manager for Kubernetes.");
        }

        [Fact]
        public void Should_ParseName()
        {
            var definition = DefinitionMarkdownParser.Parse(_definitionLines);
            definition.Name.Should().Be("helm lint");
        }
    }
}
